#!/bin/zsh

ID=99000
COVER_PATH="/tmp/cover.png"
EMPTY_COVER_PATH="$HOME/scripts/empty-album-cover.png"

getdata() {
    CURRENT_SONG_INFO="$(mpc current --wait)"
    ALBUM_PATH="$(echo /mnt/nfs/priv-media/music/$(mpc current -f %file%)|sed 's_\(.*\)/\(.*\)/\(.*\)_\1/\2/_')"
    ALBUM_COVER="$(find $ALBUM_PATH -iname 'cover.*'|grep -m1 '')"    
    RATING=$(mpc sticker "$(mpc current -f '%file%')" list |grep 'stars' |sed -e 's/[^0-9]/ /g' -e 's/^ *//g')
    FAVOURITE=$(mpc sticker "$(mpc current -f '%file%')" list |grep 'favourite' |sed -e 's/[^0-9]/ /g' -e 's/^ *//g')

    if [[ -n $RATING ]]; then
        case "$RATING" in
        "1") RATE="  " ;;
        "2") RATE="  " ;;
        "3") RATE="  " ;;
        "4") RATE="  " ;;
        "5") RATE="  " ;;
        esac
    else
        RATE="  "
    fi

    if [[ -n $FAVOURITE ]]; then
        case "$FAVOURITE" in
        "0") FAVICO=" " ;;
        "1") FAVICO=" " ;;
        esac
    else
        FAVICO=" "
    fi
}

while true; do
    getdata
    if [[ -n $ALBUM_COVER ]] && [[ -a $ALBUM_COVER ]]; then
        convert $ALBUM_COVER -resize 40x40 $COVER_PATH
    else
        convert $EMPTY_COVER_PATH -resize 40x40 $COVER_PATH
    fi

    dunstify -u normal -i "$COVER_PATH" " Now Playing $RATE$FAVICO" " $CURRENT_SONG_INFO" -r "99000"
done
