#!/bin/sh

PANEL=`xdotool search --class dwm getwindowgeometry --shell| cut -f2 -d=| sed -n 5p`
BORDER=2
SCREENX=1920
SCREENY=1080
let "fullHeightWin=$SCREENY-$PANEL-$BORDER*2"

while [ true ]; do
  WIN_ID=$(xdotool search --classname mpv-pip)
  if [ -z "$WIN_ID" ]; then
    echo "mpv window not found"
    exit 1
  fi
  windowX=`xdotool getwindowfocus getwindowgeometry --shell| cut -f2 -d=|sed -n 2p`
  windowY=`xdotool getwindowfocus getwindowgeometry --shell| cut -f2 -d=|sed -n 3p`
  windowH=`xdotool getwindowfocus getwindowgeometry --shell| cut -f2 -d=|sed -n 5p`
  if [ $windowX -lt $SCREENX ]; then
    if [ $windowX -lt 431 ]; then
      xdotool search --class mpv-up || `mpv-pip --up && sleep .35`
    elif [ $windowY -eq $PANEL ]; then
      if [ $windowH -eq $fullHeightWin ]; then
        xdotool search --class mpv-left || `mpv-pip --left && sleep .35`
      else
        xdotool search --class mpv-down || `mpv-pip --down && sleep .35`
      fi
    else
      xdotool search --class mpv-left || `mpv-pip --left && sleep .35`
    fi
  else
    xdotool search --class mpv-up || `mpv-pip --up && sleep 1`
  fi
  sleep 0.35
done
