#!/bin/sh

winId=$(xdotool search --class mpv)
if [ -z "$winId" ]; then
  echo "mpv window not found"
  exit 1
fi

# vars
moveUp=0
moveDown=0

screenX=1920
screenY=1080
winW=426
winH=240
winWM=1280
winHM=720
panel=23
margin=5

let "posX = $screenX - $winW  - $margin"
let "posY1 = $panel + $margin"
let "posY2 = $screenY - $winH - $margin"

let "posXM = $screenX / 2 - $winWM / 2"
let "posYM = $screenY / 2 - $winHM / 2"

# functions
helpFunction()
{
  echo ""
  echo "Usage: $0 --up/--down"
  echo -e "\t--up: move window to top right of the sreen"
  echo -e "\t--down: move window to bottom right of the sreen"
  echo -e "\t--center: move window to center of the screen"
  echo -e "\t--toggle: toggle between play and pause"
  echo -e "\t--close: close instance of mpv"
  exit 1
}

moveWin()
{
  xdotool windowunmap --sync $1
  xdotool windowsize $1 $4 $5
  xdotool windowmove $1 $2 $3
  xdotool set_window --classname mpv-pip $1
  xdotool set_window --overrideredirect 1 $1 # window appear on all tags without border and can't be focused'
  xdotool windowraise $1
  xdotool windowmap $1
}

centerWin()
{
  xdotool windowunmap --sync $1
  xdotool windowsize $1 $4 $5
  xdotool windowmove $1 $2 $3
  xdotool set_window --classname mpv-center $1
  xdotool set_window --overrideredirect 0 $1
  xdotool windowmap $1
}


toggleMpv()
{
  xdotool key --clearmodifiers --window $1 "p"
}

closeMpv()
{
  xdotool key --clearmodifiers --window $1 "q"
}


for i in "$@"
do
    case $i in
        --up ) moveWin $winId $posX $posY1 $winW $winH ;;
        --down ) moveWin $winId $posX $posY2 $winW $winH ;;
        --center ) centerWin $winId $posXM $posYM $winWM $winHM ;;
        --toggle ) toggleMpv $winId ;;
        --close ) closeMpv $winId ;;
        * ) helpFunction ;;
    esac
done

