#!/bin/sh

color1=14
color2=4
color3=5

fg1=`tput setaf ${color1}`
bg1=`tput setab ${color1}`
fg2=`tput setaf ${color2}`
bg2=`tput setab ${color2}`
fg3=`tput setaf ${color3}`
reset=`tput sgr0`
rev=`tput rev`

sep=" "
sep2=" "

echo -e "${fg1}${rev}   $(uname -r) ${reset}${fg1}${bg2}${sep}${reset}${fg2}${rev} $USER@$(uname -n) ${reset}${fg1}${bg2}${sep2}${bg1} ${reset}"
echo "${fg3}:: $(uptime -p |sed 's/up/uptime:/g')${reset}"
echo "${fg2}:: pkg: $(pacman -Q |wc -l)"
