#!/bin/sh

color1=8
color2=15
color3=5

fg1=`tput setaf ${color1}`
bg1=`tput setab ${color1}`
fg2=`tput setaf ${color2}`
bg2=`tput setab ${color2}`
fg3=`tput setaf ${color3}`
reset=`tput sgr0`
rev=`tput rev`

sep=" "
sep2=" "
# sep=""
# sep2=""

# echo -e "${fg1}${bg2}${rev}   $(uname -r) ${reset}${fg1}${bg2}${sep}${reset}${fg2}${bg1}${rev} $USER@$(uname -n) ${reset}${fg1}${bg2}${sep2}${bg1} ${reset}"
echo -e "  $(uname -r), $USER@$(uname -n)"
echo "${fg3}:: $(uptime -p |sed 's/up/uptime:/g')${reset}"
# echo "${fg3}:: $(df -BG | grep home | awk '{ print "home: "$4", used "$5}')${reset}"
# echo "${fg3}:: $(df -BG | grep priv-media | awk '{ print "nas: "$4", used "$5}')${reset}"
