#!/bin/sh

while true; do
    mpd_status="$(mpc | grep 'playing\|paused' | awk '{print $1}')"
    current_time="$(date '+%d/%m/%y, %H:%M CET')"

    if [ "$mpd_status" == "[playing]" ]; then
        xsetroot -name "♫ MPD:PLAYING, $current_time"
    elif [ "$mpd_status" == "[paused]" ]; then
        xsetroot -name "♫ MPD:PAUSED, $current_time"
    else
        xsetroot -name "♫ MPD:STOPPED, $current_time"
    fi
    sleep 1
done
