#!/bin/bash

helpFunction()
{
    echo ""
    echo "Usage: $0 -s [default|mpd] -i/-d [0-9]"
    echo -e "\t-s [source] is using pamixer [default] or mpc [mpd] depending on paramater"
    echo -e "\t-i [increase] icrease volume by specified number"
    echo -e "\t-d [decrease] decrease volume by specified number"
    exit 1
}

while getopts "s:i:d:" opt
do
    case "$opt" in
        s ) choosedSource="$OPTARG" ;;
        i ) increasedValue="$OPTARG" ;;
        d ) decreasedValue="$OPTARG" ;;
        ? ) helpFunction ;;
    esac
done


id="99001" # id of dunst notification
volupico="${HOME}/scripts/volup.png"
voldownico="${HOME}/scripts/voldown.png"

if [ "$choosedSource" == "mpd" ]; then
    if [[ -z "$increasedValue" ]] && [[ "$decreasedValue" =~ [0-9] ]]; then
        value="-$decreasedValue"
        mpc -q volume $value
        dunstify -u low -i $voldownico " Volume" " mpd: $(mpc volume | awk '{print substr($0,8)}' | sed 's/ //g')" -r $id
    elif [[ -z "$decreasedValue" ]] && [[ "$increasedValue" =~ [0-9] ]]; then
        value="+$increasedValue"
        mpc -q volume $value
        dunstify -u low -i $volupico " Volume" " mpd: $(mpc volume | awk '{print substr($0,8)}' | sed 's/ //g')" -r $id
    else
        helpFunction
    fi
else 
    if [[ -z "$increasedValue" ]] && [[ "$decreasedValue" =~ [0-9] ]]; then
        pamixer -d $decreasedValue
        dunstify -u low -i $voldownico " Volume" " sys: $(pamixer --get-volume-human)" -r $id
    elif [[ -z "$decreasedValue" ]] && [[ "$increasedValue" =~ [0-9] ]]; then
        pamixer -i $increasedValue
        dunstify -u low -i $volupico " Volume" " sys: $(pamixer --get-volume-human)" -r $id
    else
        helpFunction
    fi
fi
